# Generated by Django 2.1 on 2018-09-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='created_by',
            field=models.IntegerField(default=None),
        ),
    ]
