# Generated by Django 2.1 on 2018-09-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_recipes_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='created_by',
            new_name='created_by_user',
        ),
    ]
